[package]
name = "zmq-sys"
version = "0.1.1"
authors = ["Qin Zhuang <66458804@QQ.com>"]
license = "MIT"
description = "Low-level bindings to the zeromq library"
repository = "https://github.com/Ginurx/zmq-rs"
build = "build.rs"

[dependencies]
libc = "0.2.*"
