[package]
name = "zmq-ffi"
version = "0.1.2"
authors = ["Qin Zhuang <66458804@QQ.com>"]
license = "MIT"
description = "zmq-rs internal library (low-level binding to zeromq)"
repository = "https://github.com/Ginurx/zmq-rs"
build = "build.rs"

[dependencies]
libc = "0.2.*"
